#!/usr/bin/env node
'use strict';

/**
 * 黯渊崛起 内置修改器 — 安装/卸载工具 (方案 B)
 *
 * 用法:
 *   node install.js            安装（默认游戏目录）
 *   node install.js status     查看状态
 *   node install.js uninstall  卸载（还原 plugins.js）
 *   node install.js --game "游戏目录" [install|uninstall|status]
 *
 * 安装做的事:
 *   1. 备份 js/plugins.js 到本目录 backups/
 *   2. 复制 AnYuan_Trainer.js 到 <游戏>/js/plugins/
 *   3. 在 js/plugins.js 的 $plugins 末尾追加一条插件记录
 */

const fs = require('fs');
const path = require('path');

const DEFAULT_GAME_DIR = 'E:\\SteamLibrary\\steamapps\\common\\暗渊崛起 Demo';
const PLUGIN_NAME = 'AnYuan_Trainer';
const PLUGIN_FILE = 'AnYuan_Trainer.js';
const HERE = __dirname;
const BACKUP_DIR = path.join(HERE, 'backups');

function parseArgs(argv) {
    const o = { gameDir: DEFAULT_GAME_DIR, cmd: 'install' };
    for (let i = 0; i < argv.length; i++) {
        const a = argv[i];
        if (a === '--game') o.gameDir = argv[++i];
        else o.cmd = a;
    }
    return o;
}

function paths(gameDir) {
    return {
        gameDir,
        pluginsJs: path.join(gameDir, 'js', 'plugins.js'),
        pluginsDir: path.join(gameDir, 'js', 'plugins'),
        pluginDest: path.join(gameDir, 'js', 'plugins', PLUGIN_FILE),
        pkgJson: path.join(gameDir, 'package.json'),
    };
}

function checkGame(gameDir) {
    const p = paths(gameDir);
    if (!fs.existsSync(p.pluginsJs)) throw new Error('未找到 ' + p.pluginsJs + '（请用 --game 指定游戏目录）');
    if (!fs.existsSync(p.pluginsDir)) throw new Error('未找到 ' + p.pluginsDir);
    return p;
}

function readPluginsArray(text) {
    const m = text.match(/var\s+\$plugins\s*=\s*(\[[\s\S]*\]);/);
    if (!m) throw new Error('js/plugins.js 结构异常：找不到 $plugins 数组');
    return { match: m, json: m[1] };
}

// 用新的插件数组重建 plugins.js（保留文件头注释，格式与原版一致）
function writePlugins(text, arr) {
    const m = text.match(/var\s+\$plugins\s*=\s*\[/);
    const prefix = m ? text.slice(0, m.index) : '// Generated by RPG Maker.\n// Do not edit this file directly.\n';
    return prefix + 'var $plugins =\n[\n' + arr.map(e => JSON.stringify(e)).join(',\n') + '\n];\n';
}

function isInstalled(p) {
    if (!fs.existsSync(p.pluginsJs)) return false;
    const text = fs.readFileSync(p.pluginsJs, 'utf8');
    return text.includes('"name":"' + PLUGIN_NAME + '"') || text.includes('"name": "' + PLUGIN_NAME + '"');
}

// ---------------- install ----------------
function install(gameDir) {
    const p = checkGame(gameDir);

    if (isInstalled(p)) {
        // 已安装也要复制一次，使「安装 / 更新」能升级到最新版插件
        fs.copyFileSync(path.join(HERE, PLUGIN_FILE), p.pluginDest);
        console.log('✓ 修改器已安装，插件文件已更新到最新版');
        console.log('  打开方式：F10 或 右上角「修改器」按钮。');
        return;
    }

    // 1. 备份
    fs.mkdirSync(BACKUP_DIR, { recursive: true });
    const ts = new Date().toISOString().replace(/[:.]/g, '-');
    const bak = path.join(BACKUP_DIR, 'plugins.js.' + ts + '.bak');
    fs.copyFileSync(p.pluginsJs, bak);
    console.log('① 已备份 plugins.js → ' + bak);

    // 2. 复制插件
    fs.copyFileSync(path.join(HERE, PLUGIN_FILE), p.pluginDest);
    console.log('② 已复制插件 → ' + p.pluginDest);

    // 3. 注入 $plugins 记录
    let text = fs.readFileSync(p.pluginsJs, 'utf8');
    const { json } = readPluginsArray(text);
    let arr;
    try { arr = JSON.parse(json); } catch (e) { throw new Error('$plugins 解析失败: ' + e.message); }

    arr.push({
        name: PLUGIN_NAME,
        status: true,
        description: '黯渊崛起 游戏内实时修改器 (F10 打开)',
        parameters: { openKeyCode: '121', showButton: 'true' },
    });

    fs.writeFileSync(p.pluginsJs, writePlugins(text, arr), 'utf8');

    // 4. 校验
    const check = readPluginsArray(fs.readFileSync(p.pluginsJs, 'utf8'));
    const parsed = JSON.parse(check.json);
    if (!parsed.some(x => x.name === PLUGIN_NAME)) throw new Error('注入校验失败');

    console.log('③ 已注入 $plugins 记录（当前共 ' + parsed.length + ' 个插件）');
    console.log('');
    console.log('✅ 安装完成！启动游戏后：');
    console.log('   · 按 F10');
    console.log('   · 或 点右上角「修改器」按钮');
}

// ---------------- uninstall ----------------
function uninstall(gameDir) {
    const p = checkGame(gameDir);

    // 优先用备份还原
    if (fs.existsSync(BACKUP_DIR)) {
        const baks = fs.readdirSync(BACKUP_DIR).filter(f => f.startsWith('plugins.js.')).sort().reverse();
        if (baks.length) {
            fs.copyFileSync(path.join(BACKUP_DIR, baks[0]), p.pluginsJs);
            console.log('① 已用备份还原 plugins.js ← ' + baks[0]);
        }
    }

    // 无论如何，再从 plugins.js 中移除记录（防止备份不是最新）
    let text = fs.readFileSync(p.pluginsJs, 'utf8');
    const { json } = readPluginsArray(text);
    let arr;
    try { arr = JSON.parse(json); } catch (e) { throw new Error('$plugins 解析失败: ' + e.message); }
    const filtered = arr.filter(x => x.name !== PLUGIN_NAME);
    if (filtered.length !== arr.length) {
        fs.writeFileSync(p.pluginsJs, writePlugins(text, filtered), 'utf8');
        console.log('② 已从 $plugins 移除记录（' + arr.length + ' → ' + filtered.length + '）');
    }

    if (fs.existsSync(p.pluginDest)) {
        fs.unlinkSync(p.pluginDest);
        console.log('③ 已删除 ' + p.pluginDest);
    }
    console.log('✅ 卸载完成，游戏已还原为原版。');
}

// ---------------- status ----------------
function status(gameDir) {
    const p = checkGame(gameDir);
    const inst = isInstalled(p);
    console.log('游戏目录 : ' + p.gameDir);
    console.log('plugins.js: ' + (fs.existsSync(p.pluginsJs) ? '存在' : '缺失'));
    console.log('插件文件  : ' + (fs.existsSync(p.pluginDest) ? '存在' : '缺失'));
    console.log('安装状态  : ' + (inst ? '已安装 ✓' : '未安装 ✗'));
    if (fs.existsSync(BACKUP_DIR)) {
        const baks = fs.readdirSync(BACKUP_DIR).filter(f => f.startsWith('plugins.js.'));
        console.log('备份数量  : ' + baks.length + (baks.length ? '（最近: ' + baks.sort().reverse()[0] + '）' : ''));
    }
}

// ---------------- main ----------------
function main() {
    const o = parseArgs(process.argv.slice(2));
    try {
        if (o.cmd === 'install') install(o.gameDir);
        else if (o.cmd === 'uninstall') uninstall(o.gameDir);
        else if (o.cmd === 'status') status(o.gameDir);
        else { console.error('未知命令: ' + o.cmd + '（可用: install / uninstall / status）'); process.exit(1); }
    } catch (e) {
        console.error('错误: ' + e.message);
        process.exit(1);
    }
}

main();
